language: node_js
sudo: false
node_js:
- '0.10'
- '0.12'
- 'iojs'
addons:
  code_climate:
    repo_token: 70bf1755b7823ea19d6ccf000a22e73b3503fbd546c7060cf19014d9caa7369e
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c04dfa3416e63877acd9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
after_script:
  - codeclimate < lcov.info
